name: 'Docker Deploy Action'

description: >
  🪂  A Github Action to deploy pages conveniently

branding:
  icon: 'command'
  color: 'green'

inputs:
  docker_hub_username:
    description: Username for Docker Hub
    default: ${{ github.actor }}    
    required: true
  docker_hub_password:
    description: Docker Hub authentication token
    required: true
  docker_hub_token:
    description: Docker Hub authentication token
    required: true
  credentials:
    description: 'The gcloud credentials'
    required: true
  image_name:
    description: Tag to use for the new image
    default: ${{ github.action_repository }}
    required: true
  dockerfile_path:
    description: Path to the dockerfile from which to build the image
    required: true
  initiate_pauli:
    description: Build args
    required: false
    default: ""
  docker_hub_repo_short_description:
    description: Short description text for the docker hub repo
    required: true
  docker_hub_repo_readme_file_path:
    description: |
      Path of the md file which will be used as the docker hub repo readme
    required: true
  cache_src:
    description: Path for the docker cache source
    required: false
    default: /tmp/.buildx-cache
  cache_dest:
    description: Path for the docker cache destinationoh
    required: false
    default: /tmp/.buildx-cache-new
  provider:
    description: 'The deploy provider'
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  token:
    description: 'The deploy token'
    required: false
  repository:
    description: 'The deploy repository'
    default: ${{ github.repository }}
    required: false

outputs:
  command:
    description: 'The command.outputs'
    value: ${{ steps.command.outputs.stdout }}
  decays:
    description: 'The target repository'
    value: ${{ env.PGSERVICEFILE }}

runs:
  using: composite
  steps:
    - name: 🪂 Adapt feed mapping
      if: runner.os != 'Windows'
      shell: bash
      run: |
        git clone --single-branch -b gh-pages https://github.com/${{ env.TARGET_REPOSITORY }} ${{ github.action_path }}/_site &>/dev/null  
        mv -f ${{ github.action_path }}/_site/docs ${RUNNER_TEMP}/ && rm -rf ${{ github.action_path }}/_site/*
        mv -f ${{ github.workspace }}/_site/* ${{ github.action_path }}/_site/
        mv -f ${RUNNER_TEMP}/docs ${{ github.action_path }}/_site/

        rm -rf ${{ github.action_path }}/_site/.devcontainer.json ${{ github.action_path }}/_site/Dockerfile
        echo 'TARGET_REPOSITORY=${{ env.TARGET_REPOSITORY }}' > ${{ github.action_path }}/_site/.env
        echo 'LATEST_COMMIT=${{ env.LATEST_COMMIT }}' >> ${{ github.action_path }}/_site/.env 
        cat ${{ github.action_path }}/_site/.env && cat ${{ github.action_path }}/Dockerfile

    - name: 🚀 Initiate Lexer
      if: runner.os != 'Windows'
      uses: devcontainers/ci@v0.3
      id: set-output
      with:
        push: always
        imageTag: id-${{ env.ID }}
        skipContainerUserIdUpdate: true
        runCmd: ls -alR /home/runner/_site
        imageName: ${{ inputs.image_name }}
        configFile: ${{ github.action_path }}/.devcontainer.json
        env: |
          TARGET_REPOSITORY=${{ env.TARGET_REPOSITORY }}

    - name: 💎 Variables
      if: runner.os != 'Windows'
      id: variables
      shell: bash
      run: |
        BASE_NAME=$(basename ${{ inputs.image_name }})
        IFS=', '; array=($(curl -L -s 'https://registry.hub.docker.com/v2/repositories/${{ inputs.image_name }}/tags?page_size=1024' | jq -rc '."results"[]["name"]' | yq eval -P | sed "s/ /, /g"))
        for ((i=0; i < ${#array[@]}; i++)); do
          if [ "${array[$i]}" != "latest" ]; then
            HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ inputs.docker_hub_username }}\", \"password\": \"${{ inputs.docker_hub_password }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
            curl -s -i -X DELETE -H "Accept: application/json" -H "Authorization: JWT $HUB_TOKEN" https://hub.docker.com/v2/namespaces/${{ inputs.docker_hub_username }}/repositories/$BASE_NAME/tags/${array[$i]}
            echo "deleted: ${{ inputs.image_name }}:${array[$i]}"
          fi
        done

    # See https://docs.github.com/en/actions/guides
    - name: Example of using the output 
      if: runner.os == '-Windows'
      shell: bash
      run: |
        curl -s -X POST ${{ env.DATASET_URL }} \
          -H "Authorization: Bearer $(gcloud auth print-identity-token)" \
          -H "Content-Type: application/json" \
          -d '{}' | jq '.'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v1'
      if: runner.os == '-Windows'
      with:
        instance_name: 'grid-5'
        zone: 'us-central1-a'
        ssh_private_key: '${{ inputs.initiate_pauli.private_key }}'
        command: 'echo Hello world'

    # Example of using the output
    - id: 'test'
      if: runner.os == '-Windows'
      shell: bash
      run: |-
        echo '${{ steps.compute-ssh.outputs.stdout }}'
        echo '${{ steps.compute-ssh.outputs.stderr }}'

    #Ref: https://gist.github.com/xtrmstep/92aab2d465e348ce1c07ed903ca0dfb8
    - id: describe
      if: runner.os == 'Windows'
      shell: bash
      run: |-
        TF=$(choco install terraform)                
        gcloud compute instances list
        echo 'instances='$(gcloud compute instances describe grid-${{ env.IMAGE_TAG }} --zone=us-central1-a --format json) >> ${GITHUB_OUTPUT}

    - name: 🪂 Setup Runner by API
      if: runner.os == 'Windows'
      id: setup_runner
      shell: bash
      run: >
        curl -s -X POST https://us-central1-feedmapping.cloudfunctions.net/function 
        -H "Authorization: Bearer $(gcloud auth print-identity-token)" -H "Content-Type: application/json"
        -d '${{ steps.describe.outputs.instances }}'

    # Ref: https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
    - name: Configure SSH
      id: 'compute-ssh'
      if: runner.os == 'Windows'
      shell: bash
      run: |
        $IP=$(gcloud compute instances describe single-node --format='value(networkInterfaces.accessConfigs[0].natIP))
        ssh-keyscan -t rsa $IP >> $HOME/.ssh/known_hosts
        chmod 600 $HOME/.ssh/id_rsa
        cat >> $HOME/.ssh/config <<END
        Host staging
          HostName $IP
          User root
          IdentityFile $HOME/.ssh/id_rsa
          StrictHostKeyChecking no
        END
        ssh staging 'sudo whoami'
